export const SET_BPOST_STATE = 'SET_BPOST_STATE';
export const SET_USER_ERROR = 'SET_USER_ERROR';

export const GET_USERGETDATA = 'GET_USERGETDATA';
export const GET_USERGETDATA_ERROR = 'GET_USERGETDATA_ERROR';