export const SET_EPOST_STATE = 'SET_EPOST_STATE';
export const SET_USER_ERROR = 'SET_USER_ERROR';
// export const GET_USER_PROFILE = 'GET_USER_PROFILE';
// export const GET_USER_ERROR = 'GET_USER_ERROR';