export const SET_LOADER_START = 'SET_LOADER_START';
export const SET_LOADER_STOP = 'SET_LOADER_STOP';
export const SET_LOGIN_STATE = 'SET_LOGIN_STATE';
export const SET_USER_TOKEN = 'SET_USER_TOKEN';
export const SET_USER_ERROR = 'SET_USER_ERROR';

